# Generated by Django 4.2.5 on 2023-10-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_rename_image_storeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='image',
            field=models.ImageField(upload_to='uploadedImgs'),
        ),
    ]
