# Generated by Django 4.2.5 on 2023-10-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_alter_storeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeimage',
            name='cannyimg',
            field=models.ImageField(default='default.png', upload_to='cannyImgs/'),
        ),
    ]
