# Generated by Django 4.2.5 on 2023-10-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_storeimage_cannyimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='cannyimg',
            field=models.ImageField(upload_to='cannyImgs/'),
        ),
    ]
