# Generated by Django 4.2.5 on 2023-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0008_storecannyimage_remove_storeimage_cannyimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreCannyImage',
        ),
        migrations.AddField(
            model_name='storeimage',
            name='cannyimg',
            field=models.ImageField(default='default.png', upload_to='cannyImgs/'),
        ),
    ]
